name: Travlaroundtheworld
favicon: null
layout_spectrum: 0.3332823542878032
typography_spectrum: 0.07519708224572241
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8631790224462748
  lightness: 0.05580305494368076
  saturation: 0.3365648710168898
  rhythmicContrast: 0.2482422199100256
purpose: []
